apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcraibe
  labels:
    app: transcraibe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcraibe
  template:
    metadata:
      labels:
        app: transcraibe
    spec:
      containers:
      - name: backend
        image: etone/transcraibe-be:0.1
        imagePullPolicy: Always
        env:
        - name: OPENAI_ENDPOINT
          value: https://westeurope.api.cognitive.microsoft.com/
        - name: OPENAI_KEY
          valueFrom:
            secretKeyRef:
              key: attribute.primary_access_key
              name: transcraibe-oai-secret
        - name: AZURE_SPEECH_REGION
          value: westeurope
        - name: AZURE_SPEECH_KEY
          valueFrom:
            secretKeyRef:
              key: attribute.primary_access_key
              name: transcraibe-speech-secret
        ports:
        - containerPort: 8080
