azure:
    openai:
        client:
            endpoint: ${OPENAI_ENDPOINT}
            key: ${OPENAI_KEY}
        model:
            gpt: gpt-4o
            whisper: whisper
    speech:
        region: ${AZURE_SPEECH_REGION}
        key: ${AZURE_SPEECH_KEY}
endpoints:
    all:
        enabled: true
        sensitive: false
micronaut:
    application:
        name: transcraibe
    server:
        max-request-size: 524288000
        multipart:
            max-file-size: 524288000
logger:
    levels:
        transcraibe.transcribe.TranscribeService: DEBUG